/**
 * ffmpeg_handler end-to-end: real ffmpeg, real LocalStorageAdapter, fixture
 * generated by ffmpeg itself (lavfi testsrc + sine). Gated on binary presence
 * per the repo convention (ternary describe, cf. storage-integration.spec.ts).
 */
import { spawnSync } from 'child_process';
import * as fs from 'fs/promises';
import * as os from 'os';
import * as path from 'path';
import { LocalStorageAdapter } from '../../../storage/local.adapter';
import { ExpressionEvaluator } from '../../execution/expression-evaluator';
import { FfmpegCapabilityService } from '../../ffmpeg/ffmpeg-capability.service';
import { FfmpegRunnerService } from '../../ffmpeg/ffmpeg-runner.service';
import { FfmpegScratchService } from '../../ffmpeg/ffmpeg-scratch.service';
import { FfmpegHandler } from '../../handlers/ffmpeg.handler';
import type { PipelineContext } from '../../execution/pipeline-context.interface';
import type { PipelineStep } from '../../types';

const hasFfmpeg =
  spawnSync('ffmpeg', ['-version']).status === 0 && spawnSync('ffprobe', ['-version']).status === 0;

(hasFfmpeg ? describe : describe.skip)('ffmpeg_handler (integration)', () => {
  let baseDir: string;
  let scratchRoot: string;
  let adapter: LocalStorageAdapter;
  let handler: FfmpegHandler;
  const SRC_KEY = 'o/r/uploads/it/source.mp4';

  const context = () =>
    ({
      stepOutputs: {},
      metadata: { body: {}, headers: {} },
      projectId: 'p1',
    }) as unknown as PipelineContext;
  const step = (config: Record<string, unknown>): PipelineStep =>
    ({
      id: 's',
      name: 'it',
      handlerType: 'ffmpeg_handler',
      config,
      isEnabled: true,
    }) as unknown as PipelineStep;

  beforeAll(async () => {
    baseDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ffmpeg-it-storage-'));
    scratchRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'ffmpeg-it-scratch-'));
    process.env.FFMPEG_SCRATCH_DIR = scratchRoot;

    // 4s 320x240 30fps test video with a 440Hz tone, same encode profile as the ops.
    const fixture = path.join(baseDir, 'fixture.mp4');
    const gen = spawnSync('ffmpeg', [
      '-nostdin',
      '-y',
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=4:size=320x240:rate=30',
      '-f',
      'lavfi',
      '-i',
      'sine=frequency=440:duration=4',
      '-c:v',
      'libx264',
      '-preset',
      'ultrafast',
      '-pix_fmt',
      'yuv420p',
      '-c:a',
      'aac',
      '-shortest',
      fixture,
    ]);
    expect(gen.status).toBe(0);

    adapter = new LocalStorageAdapter({ localPath: baseDir });
    await adapter.upload(await fs.readFile(fixture), SRC_KEY);

    const capability = new FfmpegCapabilityService({ isEnabled: async () => true } as never);
    await capability.probe();
    handler = new FfmpegHandler(
      { register: () => undefined } as never,
      new ExpressionEvaluator(),
      capability as never,
      new FfmpegRunnerService() as never,
      new FfmpegScratchService() as never,
      { resolveOwnerRepo: async () => ({ owner: 'o', repo: 'r' }) } as never,
      adapter as never,
    );
  }, 60000);

  afterAll(async () => {
    delete process.env.FFMPEG_SCRATCH_DIR;
    await fs.rm(baseDir, { recursive: true, force: true });
    await fs.rm(scratchRoot, { recursive: true, force: true });
  });

  it('probe reports the fixture duration', async () => {
    const r = await handler.execute(
      context(),
      step({ operation: 'probe', input: 'it/source.mp4' }),
    );
    expect(r.success).toBe(true);
    expect((r.output as { duration: number }).duration).toBeCloseTo(4, 0);
  }, 30000);

  it('extract_audio writes a real 16kHz mono wav', async () => {
    const r = await handler.execute(
      context(),
      step({ operation: 'extract_audio', input: 'it/source.mp4', output: 'it/audio.wav' }),
    );
    expect(r.success).toBe(true);
    const wav = await adapter.download('o/r/uploads/it/audio.wav');
    // RIFF header + fmt: mono (ch=1 @22), 16000 Hz (@24)
    expect(wav.subarray(0, 4).toString()).toBe('RIFF');
    expect(wav.readUInt16LE(22)).toBe(1);
    expect(wav.readUInt32LE(24)).toBe(16000);
  }, 30000);

  it('slice cuts spans whose total duration probes back correctly (seam check)', async () => {
    const r = await handler.execute(
      context(),
      step({
        operation: 'slice',
        input: 'it/source.mp4',
        spans: [
          { start: 0.5, end: 1.5 },
          { start: 2.5, end: 3.5 },
        ],
        output: 'it/clip.mp4',
        audioFades: true,
      }),
    );
    expect(r.success).toBe(true);
    const probe = await handler.execute(
      context(),
      step({ operation: 'probe', input: 'it/clip.mp4' }),
    );
    expect((probe.output as { duration: number }).duration).toBeCloseTo(2, 0);
  }, 60000);

  /**
   * #818. The fixture's tone is mono; an un-narrated cut must still write the
   * 48 kHz stereo layout a narrated cut writes, or a concat of the two takes
   * the first part's layout and loses the voice after it.
   */
  it('an un-narrated cut of a mono source writes the same 48 kHz stereo audio as a narrated one', async () => {
    const audioOf = async (key: string) => {
      const local = path.join(baseDir, 'probe-' + path.basename(key));
      await fs.writeFile(local, await adapter.download(key));
      const r = spawnSync('ffprobe', [
        '-v',
        'error',
        '-select_streams',
        'a:0',
        '-show_entries',
        'stream=channels,sample_rate',
        '-of',
        'json',
        local,
      ]);
      expect(r.status).toBe(0);
      const s = (
        JSON.parse(r.stdout.toString()) as { streams: { channels: number; sample_rate: string }[] }
      ).streams[0];
      return { channels: s.channels, sampleRate: Number(s.sample_rate) };
    };
    expect((await audioOf(SRC_KEY)).channels).toBe(1);

    const voice = path.join(baseDir, 'voice.wav');
    const gen = spawnSync('ffmpeg', [
      '-nostdin',
      '-y',
      '-f',
      'lavfi',
      '-i',
      'sine=frequency=660:duration=1',
      '-ac',
      '1',
      voice,
    ]);
    expect(gen.status).toBe(0);
    await adapter.upload(await fs.readFile(voice), 'o/r/uploads/it/voice.wav');

    const plain = await handler.execute(
      context(),
      step({
        operation: 'slice',
        input: 'it/source.mp4',
        spans: [{ start: 0, end: 1 }],
        output: 'it/plain.mp4',
      }),
    );
    expect(plain.success).toBe(true);
    const voiced = await handler.execute(
      context(),
      step({
        operation: 'slice',
        input: 'it/source.mp4',
        spans: [{ start: 2, end: 3 }],
        audio: 'it/voice.wav',
        output: 'it/voiced.mp4',
      }),
    );
    expect(voiced.success).toBe(true);

    const a = await audioOf('o/r/uploads/it/plain.mp4');
    const b = await audioOf('o/r/uploads/it/voiced.mp4');
    expect(a).toEqual({ channels: 2, sampleRate: 48000 });
    expect(b).toEqual(a);

    const joined = await handler.execute(
      context(),
      step({
        operation: 'concat',
        inputs: ['it/plain.mp4', 'it/voiced.mp4'],
        output: 'it/joined.mp4',
      }),
    );
    expect(joined.success).toBe(true);
    expect(await audioOf('o/r/uploads/it/joined.mp4')).toEqual({ channels: 2, sampleRate: 48000 });
  }, 60000);

  it('concat stream-copies two slices into one clip of summed duration', async () => {
    for (const [i, span] of [
      { start: 0, end: 1 },
      { start: 2, end: 3 },
    ].entries()) {
      const r = await handler.execute(
        context(),
        step({
          operation: 'slice',
          input: 'it/source.mp4',
          spans: [span],
          output: `it/part${i}.mp4`,
        }),
      );
      expect(r.success).toBe(true);
    }
    const r = await handler.execute(
      context(),
      step({
        operation: 'concat',
        inputs: ['it/part0.mp4', 'it/part1.mp4'],
        output: 'it/final.mp4',
      }),
    );
    expect(r.success).toBe(true);
    expect((r.output as { reencoded: boolean }).reencoded).toBe(false);
    const probe = await handler.execute(
      context(),
      step({ operation: 'probe', input: 'it/final.mp4' }),
    );
    expect((probe.output as { duration: number }).duration).toBeCloseTo(2, 0);
  }, 60000);
});
