/**
 * ffmpeg_handler end-to-end: real ffmpeg, real LocalStorageAdapter, fixture
 * generated by ffmpeg itself (lavfi testsrc + sine). Gated on binary presence
 * per the repo convention (ternary describe, cf. storage-integration.spec.ts).
 */
import { spawnSync } from 'child_process';
import * as fs from 'fs/promises';
import * as os from 'os';
import * as path from 'path';
import { LocalStorageAdapter } from '../../../storage/local.adapter';
import { ExpressionEvaluator } from '../../execution/expression-evaluator';
import { FfmpegCapabilityService } from '../../ffmpeg/ffmpeg-capability.service';
import { FfmpegRunnerService } from '../../ffmpeg/ffmpeg-runner.service';
import { FfmpegScratchService } from '../../ffmpeg/ffmpeg-scratch.service';
import { FfmpegHandler } from '../../handlers/ffmpeg.handler';
import type { PipelineContext } from '../../execution/pipeline-context.interface';
import type { PipelineStep } from '../../types';

const hasFfmpeg =
  spawnSync('ffmpeg', ['-version']).status === 0 && spawnSync('ffprobe', ['-version']).status === 0;

(hasFfmpeg ? describe : describe.skip)('ffmpeg_handler (integration)', () => {
  let baseDir: string;
  let scratchRoot: string;
  let adapter: LocalStorageAdapter;
  let handler: FfmpegHandler;
  const SRC_KEY = 'o/r/uploads/it/source.mp4';

  const context = () =>
    ({
      stepOutputs: {},
      metadata: { body: {}, headers: {} },
      projectId: 'p1',
    }) as unknown as PipelineContext;
  const step = (config: Record<string, unknown>): PipelineStep =>
    ({
      id: 's',
      name: 'it',
      handlerType: 'ffmpeg_handler',
      config,
      isEnabled: true,
    }) as unknown as PipelineStep;

  beforeAll(async () => {
    baseDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ffmpeg-it-storage-'));
    scratchRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'ffmpeg-it-scratch-'));
    process.env.FFMPEG_SCRATCH_DIR = scratchRoot;

    // 4s 320x240 30fps test video with a 440Hz tone, same encode profile as the ops.
    const fixture = path.join(baseDir, 'fixture.mp4');
    const gen = spawnSync('ffmpeg', [
      '-nostdin',
      '-y',
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=4:size=320x240:rate=30',
      '-f',
      'lavfi',
      '-i',
      'sine=frequency=440:duration=4',
      '-c:v',
      'libx264',
      '-preset',
      'ultrafast',
      '-pix_fmt',
      'yuv420p',
      '-c:a',
      'aac',
      '-shortest',
      fixture,
    ]);
    expect(gen.status).toBe(0);

    adapter = new LocalStorageAdapter({ localPath: baseDir });
    await adapter.upload(await fs.readFile(fixture), SRC_KEY);

    const capability = new FfmpegCapabilityService();
    await capability.probe();
    handler = new FfmpegHandler(
      { register: () => undefined } as never,
      new ExpressionEvaluator(),
      capability as never,
      new FfmpegRunnerService() as never,
      new FfmpegScratchService() as never,
      { resolveOwnerRepo: async () => ({ owner: 'o', repo: 'r' }) } as never,
      adapter as never,
    );
  }, 60000);

  afterAll(async () => {
    delete process.env.FFMPEG_SCRATCH_DIR;
    await fs.rm(baseDir, { recursive: true, force: true });
    await fs.rm(scratchRoot, { recursive: true, force: true });
  });

  it('probe reports the fixture duration', async () => {
    const r = await handler.execute(
      context(),
      step({ operation: 'probe', input: 'it/source.mp4' }),
    );
    expect(r.success).toBe(true);
    expect((r.output as { duration: number }).duration).toBeCloseTo(4, 0);
  }, 30000);

  it('extract_audio writes a real 16kHz mono wav', async () => {
    const r = await handler.execute(
      context(),
      step({ operation: 'extract_audio', input: 'it/source.mp4', output: 'it/audio.wav' }),
    );
    expect(r.success).toBe(true);
    const wav = await adapter.download('o/r/uploads/it/audio.wav');
    // RIFF header + fmt: mono (ch=1 @22), 16000 Hz (@24)
    expect(wav.subarray(0, 4).toString()).toBe('RIFF');
    expect(wav.readUInt16LE(22)).toBe(1);
    expect(wav.readUInt32LE(24)).toBe(16000);
  }, 30000);

  it('slice cuts spans whose total duration probes back correctly (seam check)', async () => {
    const r = await handler.execute(
      context(),
      step({
        operation: 'slice',
        input: 'it/source.mp4',
        spans: [
          { start: 0.5, end: 1.5 },
          { start: 2.5, end: 3.5 },
        ],
        output: 'it/clip.mp4',
        audioFades: true,
      }),
    );
    expect(r.success).toBe(true);
    const probe = await handler.execute(
      context(),
      step({ operation: 'probe', input: 'it/clip.mp4' }),
    );
    expect((probe.output as { duration: number }).duration).toBeCloseTo(2, 0);
  }, 60000);

  it('concat stream-copies two slices into one clip of summed duration', async () => {
    for (const [i, span] of [
      { start: 0, end: 1 },
      { start: 2, end: 3 },
    ].entries()) {
      const r = await handler.execute(
        context(),
        step({
          operation: 'slice',
          input: 'it/source.mp4',
          spans: [span],
          output: `it/part${i}.mp4`,
        }),
      );
      expect(r.success).toBe(true);
    }
    const r = await handler.execute(
      context(),
      step({
        operation: 'concat',
        inputs: ['it/part0.mp4', 'it/part1.mp4'],
        output: 'it/final.mp4',
      }),
    );
    expect(r.success).toBe(true);
    expect((r.output as { reencoded: boolean }).reencoded).toBe(false);
    const probe = await handler.execute(
      context(),
      step({ operation: 'probe', input: 'it/final.mp4' }),
    );
    expect((probe.output as { duration: number }).duration).toBeCloseTo(2, 0);
  }, 60000);
});
