import { NginxConfigService } from './nginx-config.service';

/**
 * ce#584 follow-up — reported live from Umbrel.
 *
 * `PROXY_MODE=cloudflare-tunnel` makes `isExternalSslProxy()` true, so a
 * subdomain's vhost is generated by the PLATFORM-style generator. That
 * generator deliberately omitted `location = /api/storage/presigned/local`,
 * on the reasoning that "platform-mode workspaces run on managed bucket
 * storage, not the local filesystem adapter".
 *
 * Umbrel breaks that assumption: it ships `PROXY_MODE=cloudflare-tunnel`
 * AND `STORAGE_TYPE=local` (see the app-store compose). With no exception in
 * the vhost, the catch-all `location /` swallowed the presigned PUT and the
 * SPA fallback rewrote it to `<basePath>/index.html`, which the backend
 * answered 404 — every upload failed, and nothing reached disk.
 *
 * Emitting the location unconditionally is safe on a genuine platform
 * workspace: the route self-gates (`resolveLocalAdapter(...)` +
 * `supportsPresignedUrls()` 404 on a non-local adapter), so the block is
 * inert there rather than wrong.
 */
describe('generated vhosts always expose the local presigned upload route', () => {
  const project = { owner: 'bffless', name: 'handoff' } as never;

  // getBackendHost/getBackendPort read process.env directly, not ConfigService.
  const ORIGINAL_ENV = { ...process.env };
  beforeEach(() => {
    process.env.BACKEND_HOST = 'backend';
    process.env.BACKEND_PORT = '3000';
  });
  afterEach(() => {
    process.env = { ...ORIGINAL_ENV };
  });

  function buildService(): NginxConfigService {
    const featureFlags = { isEnabled: jest.fn().mockResolvedValue(false) };
    const edgeBlocklist = { getServerRules: jest.fn().mockReturnValue(''), sync: jest.fn() };
    const configService = {
      get: jest.fn((key: string, fallback?: string) => {
        const values: Record<string, string> = {
          PRIMARY_DOMAIN: 'toshimoto.dev',
          BACKEND_HOST: 'backend',
          BACKEND_PORT: '3000',
          // The Umbrel shape: tunnel in front, local storage behind.
          PROXY_MODE: 'cloudflare-tunnel',
        };
        return values[key] ?? fallback;
      }),
    };
    return new NginxConfigService(
      featureFlags as never,
      configService as never,
      edgeBlocklist as never,
    );
  }

  const subdomainMapping = {
    id: 'dom-1',
    domain: 'handoff.toshimoto.dev',
    domainType: 'subdomain',
    alias: 'handoff',
    path: '/apps/handoff/dist',
    isSpa: true,
    sslEnabled: false,
    createdAt: new Date('2026-08-01T00:00:00Z'),
  } as never;

  const customMapping = {
    ...(subdomainMapping as object),
    id: 'dom-2',
    domain: 'files.example.com',
    domainType: 'custom',
  } as never;

  it.each([
    ['subdomain', subdomainMapping],
    ['custom domain', customMapping],
  ])(
    'emits the exact-match presigned location for a %s behind an external SSL proxy',
    async (_label, mapping) => {
      const config = await buildService().generateConfig(mapping, project);

      expect(config).toContain('location = /api/storage/presigned/local');
      // Exact match is load-bearing: nginx prefers `location =` over the
      // catch-all `location /` regardless of declaration order.
      expect(config).not.toMatch(/location\s+\/api\/storage\/presigned\/local\s*\{/);
      expect(config).toContain('proxy_pass http://backend:3000');
    },
  );

  // The primary-domain generator serves an app mapped to the apex — same
  // contract, and it had none of the three until ce#584's sweep.
  it('applies the same contract to a primary-domain mapping', async () => {
    const primaryMapping = {
      ...(subdomainMapping as object),
      id: 'dom-3',
      domain: 'toshimoto.dev',
      domainType: 'subdomain',
      isPrimary: true,
      wwwBehavior: 'serve-both',
    } as never;

    const config = await buildService().generateConfig(primaryMapping, project);

    expect(config).toContain('location = /api/storage/presigned/local');
    expect(config).toContain('client_max_body_size');
    expect(config).toContain('proxy_buffer_size 16k');
  });

  it('still routes everything else into the deployment path', async () => {
    const config = await buildService().generateConfig(subdomainMapping, project);
    expect(config).toContain('/public/bffless/handoff/alias/handoff/apps/handoff/dist/');
  });

  /**
   * The CE per-domain templates carry both of these; the platform-style
   * generators never did, so an externally-proxied install (Umbrel behind a
   * Cloudflare Tunnel) inherited nginx's defaults.
   */
  it.each([
    ['subdomain', 'subdomainMapping'],
    ['custom domain', 'customMapping'],
  ])('sets a server-level client_max_body_size for a %s (nginx defaults to 1M)', async (label) => {
    const mapping = label === 'subdomain' ? subdomainMapping : customMapping;
    const config = await buildService().generateConfig(mapping, project);

    // Outside the presigned location, which has its own 200M ceiling.
    const beforePresigned = config.slice(0, config.indexOf('location = /api/storage/presigned/local'));
    expect(beforePresigned).toContain('client_max_body_size');
  });

  it.each([
    ['subdomain', 'subdomainMapping'],
    ['custom domain', 'customMapping'],
  ])(
    'sizes proxy header buffers for a %s, so a SuperTokens session refresh does not 502',
    async (label) => {
      const mapping = label === 'subdomain' ? subdomainMapping : customMapping;
      const config = await buildService().generateConfig(mapping, project);

      // At nginx's 4k default, a successful /api/auth/session/refresh
      // overflows the header buffer and returns 502 (ce#370).
      expect(config).toContain('proxy_buffer_size 16k');
      expect(config).toContain('proxy_buffers 8 16k');
      expect(config).toContain('proxy_busy_buffers_size 32k');
    },
  );

  it('streams the upload body through rather than spooling it in nginx', async () => {
    const config = await buildService().generateConfig(subdomainMapping, project);
    const block = config.slice(config.indexOf('location = /api/storage/presigned/local'));
    expect(block).toContain('proxy_request_buffering off');
  });
});
